<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.llwallet.interfaces.test.api.online.personal.CashoutNowApplyTest" tests="1" time="2.183" ignored="0" failures="1" timestamp="01 三月 2017 19:57:29 GMT" skipped="0" hostname="LT-jiangxm" errors="0">
  <testcase name="cashoutNowApply" time="2.183" classname="com.llwallet.interfaces.test.api.online.personal.CashoutNowApplyTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.online.personal.CashoutNowApplyTest.cashoutNowApply(CashoutNowApplyTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- cashoutNowApply -->
</testsuite> <!-- com.llwallet.interfaces.test.api.online.personal.CashoutNowApplyTest -->
