<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LT-jiangxm" name="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest" tests="34" failures="0" timestamp="17 Nov 2017 07:47:22 GMT" time="17.846" errors="7">
  <testcase name="threeFactorsSignApply" time="0.443" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.194" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.451" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.670" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.646" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest.threeFactorsSignApply(ThreeFactorsSignApplyTest.java:66)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- threeFactorsSignApply -->
  <testcase name="threeFactorsSignApply" time="0.170" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.158" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.181" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.331" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.161" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.161" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.695" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.211" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.156" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.276" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.276" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.181" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="3.765" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest.threeFactorsSignApply(ThreeFactorsSignApplyTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- threeFactorsSignApply -->
  <testcase name="threeFactorsSignApply" time="0.603" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest.threeFactorsSignApply(ThreeFactorsSignApplyTest.java:66)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- threeFactorsSignApply -->
  <testcase name="threeFactorsSignApply" time="0.185" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.176" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.220" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="1.050" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest.threeFactorsSignApply(ThreeFactorsSignApplyTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- threeFactorsSignApply -->
  <testcase name="threeFactorsSignApply" time="0.523" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="1.389" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest.threeFactorsSignApply(ThreeFactorsSignApplyTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- threeFactorsSignApply -->
  <testcase name="threeFactorsSignApply" time="1.254" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest.threeFactorsSignApply(ThreeFactorsSignApplyTest.java:66)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- threeFactorsSignApply -->
  <testcase name="threeFactorsSignApply" time="0.289" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.478" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest.threeFactorsSignApply(ThreeFactorsSignApplyTest.java:66)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- threeFactorsSignApply -->
  <testcase name="threeFactorsSignApply" time="0.179" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.158" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.436" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="1.432" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.174" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.174" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest"/>
</testsuite> <!-- com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignApplyTest -->
