<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LT-jiangxm" name="com.llwallet.interfaces.test.api.test.personal.Balance2OtherCardTest" tests="1" failures="0" timestamp="11 Sep 2017 03:29:32 GMT" time="1.838" errors="1">
  <testcase name="balance2OtherCard" time="1.838" classname="com.llwallet.interfaces.test.api.test.personal.Balance2OtherCardTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.Balance2OtherCardTest.balance2OtherCard(Balance2OtherCardTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- balance2OtherCard -->
</testsuite> <!-- com.llwallet.interfaces.test.api.test.personal.Balance2OtherCardTest -->
