<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.llwallet.interfaces.test.api.test.secured.SecuredPayConfirmTest" tests="1" time="1.480" ignored="0" failures="1" timestamp="06 三月 2017 08:53:29 GMT" skipped="0" hostname="LT-jiangxm" errors="0">
  <testcase name="securedPayConfirm" time="1.480" classname="com.llwallet.interfaces.test.api.test.secured.SecuredPayConfirmTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.secured.SecuredPayConfirmTest.securedPayConfirm(SecuredPayConfirmTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- securedPayConfirm -->
</testsuite> <!-- com.llwallet.interfaces.test.api.test.secured.SecuredPayConfirmTest -->
