<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LT-jiangxm" name="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignVerifyTest" tests="1" failures="0" timestamp="17 Nov 2017 07:37:23 GMT" time="2.491" errors="1">
  <testcase name="threeFactorsSignVerify" time="2.491" classname="com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignVerifyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignVerifyTest.threeFactorsSignVerify(ThreeFactorsSignVerifyTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- threeFactorsSignVerify -->
</testsuite> <!-- com.llwallet.interfaces.test.api.test.personal.ThreeFactorsSignVerifyTest -->
