<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LT-jiangxm" name="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest" tests="159" failures="0" timestamp="2 Nov 2017 13:27:27 GMT" time="88.355" errors="31">
  <testcase name="spayApply" time="0.960" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.172" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.128" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.169" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.152" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.149" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.153" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.840" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.198" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.117" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.133" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.303" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.172" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.177" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.810" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.128" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.158" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.142" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.125" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.159" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="3.457" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.158" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.214" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.433" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.146" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.181" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.270" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.119" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.084" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.118" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.966" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.124" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.008" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.706" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.141" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.493" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="1.349" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.151" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="2.483" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.156" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.813" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.969" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.765" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.858" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="1.439" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.131" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.203" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.117" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.249" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.165" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.865" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.224" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.228" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.122" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.949" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="2.292" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.176" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.148" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.893" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.118" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.133" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.963" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.908" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.841" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.153" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.065" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.172" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.227" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.513" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.237" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.144" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.757" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.159" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.129" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.841" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.768" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.775" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.147" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.191" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.870" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.117" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.168" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.161" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.123" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.211" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.913" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.120" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.125" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.375" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.796" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.089" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.188" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.496" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.123" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="2.358" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.172" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.752" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.165" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.115" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.122" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="2.664" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.146" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.932" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.949" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.824" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.158" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.181" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.155" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.156" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.145" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.987" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.919" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.160" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.146" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.146" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.146" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.136" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.165" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.664" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.167" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.131" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.176" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.835" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.120" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.907" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.757" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.146" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.125" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.156" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.165" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.730" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.750" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.123" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.167" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="2.183" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.123" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.145" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.156" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.156" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.819" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.151" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.148" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.676" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.180" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.148" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.641" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.150" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.785" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.374" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.119" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.793" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SpayApplyTest.spayApply(SpayApplyTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- spayApply -->
  <testcase name="spayApply" time="0.126" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.147" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.823" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.005" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.909" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.155" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="1.559" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
  <testcase name="spayApply" time="0.142" classname="com.llwallet.interfaces.test.api.test.personal.SpayApplyTest"/>
</testsuite> <!-- com.llwallet.interfaces.test.api.test.personal.SpayApplyTest -->
