<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LT-jiangxm" name="com.llwallet.interfaces.test.api.online.custom.SecpayRefundOnlineTest" tests="1" failures="1" timestamp="20 Dec 2017 14:21:17 GMT" time="2.510" errors="0">
  <testcase name="secpayRefund" time="2.510" classname="com.llwallet.interfaces.test.api.online.custom.SecpayRefundOnlineTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.online.custom.SecpayRefundOnlineTest.secpayRefund(SecpayRefundOnlineTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- secpayRefund -->
</testsuite> <!-- com.llwallet.interfaces.test.api.online.custom.SecpayRefundOnlineTest -->
